-- Force-fix waitlist_entries.status constraints.
-- This is V8 because Flyway will not run V7 again if V7 was already recorded in flyway_schema_history.
-- The original V1 unnamed check is generated by PostgreSQL as waitlist_entries_status_check,
-- and it does not allow the "skipped" status.

alter table waitlist_entries
    drop constraint if exists waitlist_entries_status_check;

alter table waitlist_entries
    drop constraint if exists chk_waitlist_entries_status;

alter table waitlist_entries
    add constraint waitlist_entries_status_check
    check (status in ('waiting', 'notified', 'skipped', 'seated', 'left', 'expired'));
